# Generated by Django 5.2.5 on 2025-08-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0003_alter_fooditem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='slug',
            new_name='item_slug',
        ),
    ]
