# Generated by Django 5.2.5 on 2025-08-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0004_rename_slug_fooditem_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='category_name',
            new_name='category',
        ),
    ]
