# Generated by Django 5.2.5 on 2025-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0005_rename_category_name_fooditem_category'),
        ('vendor', '0002_alter_vendor_vendor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name'), name='unique_item_category'),
        ),
    ]
