# Generated by Django 5.2.5 on 2025-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0006_alter_category_category_name_and_more'),
        ('vendor', '0002_alter_vendor_vendor_license'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_item_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name', 'slug'), name='unique_item_category'),
        ),
    ]
