# Generated by Django 5.2.5 on 2025-08-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0007_remove_category_unique_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
