# Generated by Django 5.2.5 on 2025-08-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0009_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='on_hand_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
